#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 21 20:40:26 CET 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TB_SYNC_FIFO_behav -key {Behavioral:sim_1:Functional:TB_SYNC_FIFO} -tclbatch TB_SYNC_FIFO.tcl -log simulate.log"
xsim TB_SYNC_FIFO_behav -key {Behavioral:sim_1:Functional:TB_SYNC_FIFO} -tclbatch TB_SYNC_FIFO.tcl -log simulate.log

